name: jobfortech2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_custom_dropdown: ^1.5.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_typeahead: ^4.8.0
  get: 4.6.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl_phone_field: ^3.2.0
  percent_indicator: ^4.2.3

  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^23.1.40
  url_launcher: ^6.1.14
  buttons_tabbar: ^1.3.8
  intl: ^0.18.1
  like_button: ^2.0.5


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


flutter_native_splash:
  color: "#0371D8"
  image: assets/images/logo_splash.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/logo_splash_androd_12.png



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/json/
