name: jobfortech2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_custom_dropdown: ^1.5.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_typeahead: ^4.8.0
  get: 4.6.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl_phone_field: ^3.2.0
  percent_indicator: ^4.2.3

  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^23.1.40
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/json/
