name: jobfortech
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_custom_dropdown: ^1.5.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.7
  get: 4.6.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/json/
